version: '3.9'

services: 
  jupyterlab:
    image: alivatan1999/problem5:v1
    ports:
      - "8888:8888"
    volumes:
      - ./problem5:/problem5
    env_file:
      - .env
    networks:
      - dbnetwork

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - dbnetwork

volumes:
  postgresdata:

networks:
  dbnetwork:
